version: '3.4'

services:
  egdebookingsystem:
    image: ${DOCKER_REGISTRY-}egdebookingsystem
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:80"
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
    depends_on:
        - db
  db:
     image: "mcr.microsoft.com/mssql/server"
     ports:
        - "1433"   
     environment:
         SA_PASSWORD: "Password123@"
         ACCEPT_EULA: "Y"